### ISSUE TITLE
Completely Lost

### ISSUE THREAD

**Issue by tgwaste** [pmmp/DevTools#48]
So first off:
```
[13:00:21] [Server thread/INFO]: Starting Minecraft: Bedrock Edition server version v1.14.60
[12:58:38] [Server thread/ERROR]: Could not load plugin 'DevTools': Incompatible API version (plugin requires one of: 4.0.0)
```
Trying to compile from command line
```
# /usr/bin/php7.2 -dphar.readonly=0 /tmp/DevTools.phar --make /root/minecraft/dev/ExamplePlugin --out /tmp/example.phar

PHP Fatal error:  Uncaught Error: Call to undefined function yaml_parse_file() in phar:///tmp/DevTools.phar/src/DevTools/ConsoleScript.php:134
Stack trace:
#0 phar:///tmp/DevTools.phar/src/DevTools/ConsoleScript.php(221): generatePluginMetadataFromYml('/root/minecraft...')
#1 phar:///tmp/DevTools.phar/src/DevTools/ConsoleScript.php(238): main()
#2 phar:///tmp/DevTools.phar/stub.php(3): require('phar:///tmp/Dev...')
#3 /tmp/DevTools.phar(1): require('phar:///tmp/Dev...')
#4 {main}
  thrown in phar:///tmp/DevTools.phar/src/DevTools/ConsoleScript.php on line 134
```

What am I missing here?

**Comment by jasonw4331** [comment]
You're using the wrong branch

**Comment by tgwaste** [comment]
oh... duh.  thanks!

**Comment by dktapps** [comment]
this issue tracker isn't a support forum, please stop using it as one...

**Comment by tgwaste** [comment]
It seems like the master branch should be what everyone would be using and a subbranch would be made for future and or in development api versions.
¯\_(ツ)_/¯

P.S. Let me know if you still need a laptop.
